<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Network" nsURI="roadnetwork" nsPrefix="rn">
  <eClassifiers xsi:type="ecore:EClass" name="Section">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" upperBound="-1"
        eType="#//Representation" eOpposite="#//Representation/sections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Representation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" lowerBound="1"
        upperBound="-1" eType="#//Section" eOpposite="#//Section/representations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalRepresentation" eSuperTypes="#//Representation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mesh" lowerBound="1" eType="#//Mesh"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1" eType="#//Area"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//PhysicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="#//AssetType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssetType">
    <eLiterals name="Barrier"/>
    <eLiterals name="Curb" value="1"/>
    <eLiterals name="Deck" value="2"/>
    <eLiterals name="FenceSolid" value="3"/>
    <eLiterals name="FenceChain" value="4"/>
    <eLiterals name="Fill" value="5"/>
    <eLiterals name="Grass" value="6"/>
    <eLiterals name="Lamp" value="7"/>
    <eLiterals name="Median" value="8"/>
    <eLiterals name="Sidewalk" value="10"/>
    <eLiterals name="Support" value="11"/>
    <eLiterals name="Pillar" value="12"/>
    <eLiterals name="Retainer" value="13"/>
    <eLiterals name="Wall" value="14"/>
    <eLiterals name="Pipe" value="15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//PhysicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="#//LineType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//LineColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineType">
    <eLiterals name="Dashed"/>
    <eLiterals name="Solid" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineColor">
    <eLiterals name="White"/>
    <eLiterals name="Yellow" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mark" eSuperTypes="#//PhysicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="#//MarkType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MarkType">
    <eLiterals name="Chevron"/>
    <eLiterals name="Cross" value="1"/>
    <eLiterals name="Crossing" value="2"/>
    <eLiterals name="Cyclist" value="3"/>
    <eLiterals name="Diagonal" value="4"/>
    <eLiterals name="Perpendicular" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aabbMin" unique="false"
        lowerBound="3" upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aabbMax" unique="false"
        lowerBound="3" upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mesh">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" unique="false"
        lowerBound="3" upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Surface" eSuperTypes="#//PhysicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" lowerBound="1"
        eType="#//SurfaceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topMaterial" upperBound="-1"
        eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="midMaterial" lowerBound="1"
        upperBound="-1" eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowMaterial" upperBound="-1"
        eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defect" upperBound="-1"
        eType="#//SurfaceDefect" eOpposite="#//SurfaceDefect/surface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="carsPerHour" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lanes" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMaterial" lowerBound="1"
        eType="#//Material"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SurfaceType">
    <eLiterals name="Pavement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MaterialType">
    <eLiterals name="FineAggregates" value="2"/>
    <eLiterals name="CoarseAggregates" value="3"/>
    <eLiterals name="Bitumen" value="4"/>
    <eLiterals name="PortlandCement" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//MaterialType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SurfaceDefect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SurfaceDefectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" unique="false"
        lowerBound="3" upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="surface" lowerBound="1"
        eType="#//Surface" eOpposite="#//Surface/defect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SurfaceDefectType">
    <eLiterals name="Potholes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drone">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" unique="false"
        lowerBound="3" upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
